#! /bin/bash

var=fpx
run_type=map
ts=$(date "+%H%M%S.%d%m%Y")

make -j4

#./darknet detector $run_type cfg/coco.data cfg/yolov3-tiny.cfg \
#	yolov3-tiny.weights 2>&1 data/dog.jpg\
#	| tee log/arm.$run_type.$var.$ts

./darknet detector $run_type cfg/coco.data cfg/yolov3-tiny.cfg \
	yolov3-tiny.weights 2>&1 \
	| tee log/arm.$run_type.$var.$ts

gprof darknet gmon.out > perf_results/darknet.perf.arm.$var.$run_type.$(date "+%H%M%S.%d%m%Y") 
